### ISSUE TITLE
Problem creating the card

### ISSUE THREAD

**Issue by KitTeaCup27** [teclu/kudopepega#1]
i believe i've filled out everything correctly but when i try to create the board i get "(X) Fetch Error" at the top of my screen while sent back to the homepage guh :c

Edit: i also tried on mobile and got the same problem AHUUU

**Comment by teclu** [comment]
Hi @KitTeaCup27, the `Fetch Error` notification will only appear when the spreadsheet specified is inaccessible.

Make sure you have done the following:

- Click on `Change to anyone with the link`.

![](https://user-images.githubusercontent.com/27724529/138104154-182f7e24-29d6-4612-897e-6fa452932750.png)

- You should see a `Permission updated` notification and the following details:

![image](https://user-images.githubusercontent.com/27724529/138104324-1e5c931d-06df-47c7-9506-aa98e83298f2.png)

If the error is still persisting, could you take a screenshot of the `console` and `network` `Fetch/XHR` log?
