### ISSUE TITLE
Issue regarding the google form link

### ISSUE THREAD

**Issue by jprosu** [teclu/kudopepega#2]
Hi there,

I am trying to make a board for a xmas 

When i came across pasting my pre-filled google forms, it said invalid for some reason

Any ideas on how to fix this 
<img width="623" alt="Screen Shot 2022-12-23 at 6 43 04 pm" src="https://user-images.githubusercontent.com/121283780/209295091-7dbf3dc7-a7b3-4734-b2cc-78ddf04eb73d.png">

**Comment by teclu** [comment]
Hi @jprosu,

Before generating the pre-filled link, did you fill in the text fields? For example:

<img width="685" alt="Screenshot 2022-12-23 at 4 31 29 PM" src="https://user-images.githubusercontent.com/27724529/209301549-11f382c2-88bd-4aa1-b183-e3e237ffac93.png">

Try doing the above before generating the pre-filled link and pasting it. It should look something like this (there should be some `entry.<...>` query parameters at the back of the link):
```
https://docs.google.com/forms/d/e/<...>/viewform?usp=pp_url&entry.<...>=jprosu&entry.<...>=test+message+here
```

Hope this helps! 😄
